languageCode = "zh-cn"
languageName = "Chinese"
weight = 1
title = "梦里不知身是客"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Your name here"
  image = "img/blowfish_logo.png"
  headline = "I'm only human"
  bio = "A little bit about you"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { facebook = "https://facebook.com/username" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/NeoZephyr" },
#     { google = "https://www.google.com/" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { reddit = "https://reddit.com/user/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { telegram = "https://t.me/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { youtube = "https://youtube.com/username" },
  ]
